version: '3.5'

networks: 
  localdev:
    name: localdev

services:
  main-api:
    build: TweetBook/
    restart: always
    ports: 
      - 7000:80
    depends_on: 
      - db-server
    networks:
      - localdev

  postgres_image:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=oliver
      - POSTGRES_PASS=oliver
      - POSTGRES_DB=assessment
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    networks:
      - localdev
