From microsoft/dotnet:3.1 sdk as build

ARG BUILDCONFIG-RELEASE
ARG VERSION=1.0.0

COPY TweetBook.csproj /build/

RUN dotnet restore ./build/TweetBook.csproj.user

COPY . ./build/
WORKDIR /build/
RUN dotnet publish ./TweetBook.csproj.user -c $BUILDCONFIG -o out /p:Version=$VERSION

From microsoft/dotnet:3.1-aspcore-runtime
WORKDIR /app

COPY --from=build /build/out .

ENTRYPOINT ["dotnet", "TweetBook.dll"]
